### ISSUE TITLE
Crash occurs when creating too many static meshes

### ISSUE THREAD

**Issue by sami016** [bepu/bepuphysics2#45]
## Description

 - Writing a system to spawn in terrain chunks around a central point.
 - For each terrain chunk, I create a static mesh from a height map, then add a static to the simulation with a collidable description for that mesh.
 - This works fine, up until the 258th chunk is spawned, at which point the program consistently crashes.
   - Currently 1922 triangles per mesh.
 - "Game.exe has stopped working" shown by windows, no exceptions thrown.
 - Event viewer doesn't show much useful information, but I'm seeing `Faulting module name: clr.dll, version: 4.7.3163.0`.

It's possible that this is a bug in some unmanaged code that occurs when the buffer overflows, but either way it seems like this should be handled more gracefully, throwing an exception when this happens.

Any help resolving this issue would be greatly appreciated.

## Environment Information

 - Version: BepuPhysics 2.0.0.0-beta, BepuUtilities 2.0.0.0-beta
 - OS: Windows 10 x64

**Comment by RossNordby** [comment]
Having trouble reproducing this in the demos. There is a known bug that can trigger in some similar cases (insertion can lead to a bad tree), but that should show up as a stack overflow exception in the broad phase. What you've described sounds more like a capacity resizing bug.

Could you try reproducing it in one of the demos?

(There was a resizing bug in the MeshCache of the DemoRenderer, though. Should be fixed in bdf5f1fd694f3f9897960d67e8ab4a899b24e653.)

**Comment by sami016** [comment]
Tried reproducing on a demo, but was unable to make the issue manifest. It's quite possible that this fix has resolved the problem on the latest code base.

**Comment by vpenades** [comment]
Maybe it's related to [this one](https://github.com/dotnet/coreclr/issues/19022)?  

MS already fixed it in master, but the fix has not been released yet, so it's still a problem for everybody.

@sami016 could you try to verify if the exception is an AccessViolationException?   that kind of exceptions cannot be trapped with a normal try catch block, and unless you're using unsafe pointer arithmetics, it usually indicates a net framework bug.

You can enable Net.Framework source code debugging by following [these instructions](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-dotnet-framework-source?view=vs-2017).

This way, if it crashes in a net framework call, you'll get more information about the cause.

**Comment by sami016** [comment]
@vpenades I've since swapped to using latest debugs off master within my project, and it seems to have cleared up the issue. If I see any resurgence I'll be sure to use the method described above - most useful thanks!
